### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [nathanclevenger/beautiful.json.fyi#1]
- [ ] Figure out architecture of a cross-platform and cross-browser plugin
- [ ] Support Safari
- [ ] Support Chrome
- [ ] Support Edge
- [ ] Support Firefox
- [ ] Support Safari on iOS
- [ ] Support Safari on iPad OS
- [ ] Support Chrome on iOS
- [ ] Support Chrome on Android
- [ ] Figure out way to detect browser plugin server-side
